title: Developers
email: woojiahao1234@gmail.com
description: >-
  Developer documentation about all things Git-Mastery
baseurl: "/developers"
url: "https://git-mastery.github.io"
permalink: pretty

mermaid:
  version: "9.1.6"

theme: just-the-docs
plugins:
  - jekyll-feed

callouts:
  note:
    title: Note
    color: blue

  reference:
    title: Reference
    color: green

  warning:
    title: Warning
    color: yellow
